### ISSUE TITLE
Firefox IndexedDB AbortError during sync

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#221]
User farribeiro reported session backup not always working for older messages, and while reporting also hit a sync error after a while where reading from roomMembers failed because the transaction (or a request, but nothing aborts request currently?) was aborted... I wonder if this error means an explicit abort was called or it could also be due to the internals of indexeddb aborting for some reason ...

This is on Firefox 86:

![image](https://user-images.githubusercontent.com/274386/107367309-0e939d00-6ad7-11eb-95f3-54721425053c.png)

From attached logs: `IDBRequest failed on hydrogen_session_3915405544054394.roomMembers: (name: AbortError) (code: 20) A request was aborted, for example through a call to IDBTransaction.abort.`

It looks like the room appears in the incremental sync for the first time here `!FoMGdgXlowYswYsCcO:matrix.org` (calculate amount of events synced from persister load), wonder if the error is specific to this room.

Full logs: [farribeiro.log](https://github.com/vector-im/hydrogen-web/files/5951486/farribeiro.log)

**Comment by bwindels** [comment]
looks like another instance of this [was reported by MTRNord](https://matrix.to/#/!gnUVJvTOKImfOaWAYA:matrix.org/$oNL7jh32gfofZDrU5WcabgkCZdlUpHX8y-XMdiSOhUA?via=matrix.org&via=mozilla.org&via=privacytools.io) earlier in November last year:

> **MTRNord**: Hm I got  a small issue. It says "Sync failed because of StorageError: IDBRequest failed on hydrogen_session_2507730060814991.roomMembers: (name: AbortError) (code: 20) The transaction was aborted, so the request cannot be fulfilled.". Reload does not fix it. and 500GB of free space this time around should be "just enough" ^^
> **MTRNord**:
```
Could not abort sync transaction, the sync response was probably only partially written and may have put storage in a inconsistent state. DOMException: Failed to execute 'abort' on 'IDBTransaction': The transaction has finished.
    at Transaction.abort (https://hydrogen.element.io/hydrogen-1718798642.js:1254:19)
    at Sync._syncRequest (https://hydrogen.element.io/hydrogen-1718798642.js:5100:25)
    at async Sync._syncLoop (https://hydrogen.element.io/hydrogen-1718798642.js:5030:36)
```

> **Bruno**: interesting, any other error logged?
> **MTRNord**: No but the ubports  room is what I suspect to be the reason as also Element Web fails to resolve the correct room Name 🤔
> **MTRNord**: I think that is a broken v1 room 🤔
> **Bruno**: #ubports:matrix.org?
> **MTRNord**: Yeah

**Comment by bwindels** [comment]
The room where it blew up for farribeiro was `!FoMGdgXlowYswYsCcO:matrix.org` aka `#rockylinux-general:matrix.org` which is a version 6 room. Also, it was the first room response processed in that sync, so might be more due to that than a wrong version or the room being broken, as MTRNord reported.

**Comment by bwindels** [comment]
Using https://github.com/vector-im/hydrogen-web/issues/180 as the main issue for this.
